GET http://localhost:5244/games/

###
GET http://localhost:5244/games/4

###
POST http://localhost:5244/games
Content-Type: application/json

{
    "name": "Item 7",
    "genreId": 2,
    "price": 29.99,
    "releaseDate": "2011-12-18"
}

###
PUT http://localhost:5244/games/2
Content-Type: application/json

{
    "name": "Item 2 new",
    "genre": "genre Item 2 new",
    "price": 59.99,
    "releaseDate": "2021-11-21"
}

###
DELETE http://localhost:5244/games/2