GET http://localhost:5244/games/

###
GET http://localhost:5244/games/3

###
POST http://localhost:5244/games
Content-Type: application/json

{
    "name": "Item 4",
    "genre": "genre Item 4",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5244/games/2
Content-Type: application/json

{
    "name": "Item 2 new",
    "genre": "genre Item 2 new",
    "price": 59.99,
    "releaseDate": "2021-11-21"
}